image: maven:latest

stages:
  - build
  - release

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:scarlet:jar:
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_IID
  artifacts:
    paths:
      - target/*-fat.jar
    expire_in: 1 hour
  script:
    - mvn clean package

# TODO: 
#   - use tags (+rule)
#   - automate the release

build:scarlet:beta:version:
  stage: build
  #variables:
  #  file_name: scarlet-0.0.1-SNAPSHOT-fat.jar
  #  version: "0.0.1"
  rules:
    - if: $CI_COMMIT_TAG
    #- if: $CI_COMMIT_BRANCH == "master"
  artifacts:
    paths:
      - target/${file_name}
    expire_in: 1 hour
    reports:
      dotenv: version.env
  script: |
    # build the application
    mvn clean package
    #echo "RELEASE_PATH=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/scarlet/${version}/${file_name}" > version.env
    #echo "VERSION=${version}" >> version.env

    RELEASE_PATH=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/scarlet/${CI_COMMIT_TAG}/scarlet-${CI_COMMIT_TAG}-SNAPSHOT-fat.jar
    echo "RELEASE_PATH=$RELEASE_PATH" > release.env

    # then publish it to the generic registry
    curl --header "JOB-TOKEN:$CI_JOB_TOKEN" \
         --upload-file target/scarlet-${CI_COMMIT_TAG}-SNAPSHOT-fat.jar \
         "$RELEASE_PATH"

release:scarlet:beta:version:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  variables: 
    asset_link: |
      {
        "name":"Scarlet v${CI_COMMIT_TAG}", 
        "url":"${RELEASE_PATH}"
      }
  rules:
    - if: $CI_COMMIT_TAG
    #- if: $CI_COMMIT_BRANCH == "master"
  script: |
    echo "🚀 $RELEASE_PATH"
    echo "📦 $CI_COMMIT_TAG"
    release-cli create \
      --name "Scarlet v${CI_COMMIT_TAG}" \
      --description "Beta release v${CI_COMMIT_TAG}" \
      --assets-link "${asset_link}"







