image: maven:latest

stages:
  - build
  - release

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:scarlet:jar:
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_IID
  artifacts:
    paths:
      - target/*-fat.jar
    expire_in: 1 hour
  script:
    - mvn clean package

# TODO: 
#   - use tags (+rule)
#   - automate the release

build:scarlet:beta:version:
  stage: build
  variables:
    file_name: scarlet-0.0.0-SNAPSHOT-fat.jar
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    paths:
      - target/${file_name}
    expire_in: 1 hour
  script: |
    # build the application
    mvn clean package
    echo "RELEASE_PATH=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/scarlet/${CI_COMMIT_TAG}/${file_name}" > version.env
    #echo "VERSION=${version}" >> version.env
    # then publish it to the generic registry
    curl --header "JOB-TOKEN:$CI_JOB_TOKEN" \
         --upload-file target/${file_name} \
         "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/scarlet/${CI_COMMIT_TAG}/scarlet-${CI_COMMIT_TAG}.jar"

release:scarlet:beta:version:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  variables: 
    asset_link: |
      {
        "name":"Scarlet v${CI_COMMIT_TAG}", 
        "url":"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/scarlet/${CI_COMMIT_TAG}/scarlet-${CI_COMMIT_TAG}.jar"
      }
  rules:
    - if: $CI_COMMIT_TAG
  script: |
    release-cli create \
      --name "Scarlet v${CI_COMMIT_TAG}" \
      --tag-name v${CI_COMMIT_TAG} \
      --description "Beta release v${CI_COMMIT_TAG}" \
      --assets-link "${asset_link}"







