image: maven:latest

stages:
  - build

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:scarlet:jar:
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_IID
  artifacts:
    paths:
      - target/*-fat.jar
    expire_in: 1 hour
  script:
    - mvn clean package

#TODO: tag
#TODO: automate the release
build:scarlet:beta:version:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  artifacts:
    paths:
      - target/*-fat.jar
    expire_in: 1 hour
    #expire_in: never
  script:
    #- mvn clean package
    - curl --version

